# Generated by Django 5.1.7 on 2026-07-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
